import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SupabaseAuthProvider } from "@/components/SupabaseAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        '''        <SupabaseAuthProvider>
          <nav className="flex justify-center space-x-4 p-4 bg-gray-100">
            <a href="/create-poll">Create Poll</a>
            <a href="/polls">All Polls</a>
          </nav>
          {children}
        </SupabaseAuthProvider>'''
      </body>
    </html>
  );
}
